spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: app
    password: app123!@#
    url: "jdbc:mysql://localhost:3306/delivery_store?useSSL=false&allowPublicKeyRetrieval=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: delivery-payment-group

server:
  port: 20002
  role-name: delivery-store-admin

jwt:
  key: fastcampus-education-kotlin-project
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

logging:
  level:
    root: info